before_install:
- travis_retry gem install bundler
rvm:
- 1.9.3
- 2.0.0
- 2.1
- ruby-head
- rbx-2
- jruby
matrix:
  allow_failures:
  - rvm: rbx-2
  - rvm: jruby
  - rvm: ruby-head
  fast_finish: true
notifications:
  email: true
services:
- redis
